services:
  db:
    image: postgres:16.0
    container_name: database-auth-tests
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
      - POSTGRES_DB=auth-tests
    volumes:
      - auth-tests:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  auth-tests: